### ISSUE TITLE
bug in separator in groups digest

### ISSUE THREAD

**Issue by 91DarioDev** [91DarioDev/TopSupergroupsBot#10]
```
Traceback (most recent call last):
  File "**/topsupergroups/utils.py", line 190, in sep
    locale.setlocale(locale.LC_ALL, lang)
  File "/usr/lib/python3.5/locale.py", line 594, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telegram/utils/promise.py", line 42, in run
    self._result = self.pooled_function(*self.args, **self.kwargs)
  File "***/topsupergroups/digest_supergroups.py", line 231, in weekly_groups_digest
    diff_msg, percent_msg = diff_percent(msgs_new, msgs_old, lang)
  File "***/topsupergroups/digest_supergroups.py", line 285, in diff_percent
    diff_s = utils.sep(diff, lang) if diff < 0 else "+"+utils.sep(diff, lang)
  File "***/topsupergroups/utils.py", line 192, in sep
    locale.setlocale(locale.LC_ALL, 'en')
  File "/usr/lib/python3.5/locale.py", line 594, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```

**Comment by 91DarioDev** [comment]
https://github.com/91DarioDev/TopSupergroupsBot/blob/bfd4a2f78b5b54f8ee5cbb4be3b09e82b9bf61d3/digest_supergroups.py#L287

**Comment by 91DarioDev** [comment]
The line is this and not the one in the previous message 

https://github.com/91DarioDev/TopSupergroupsBot/blob/bfd4a2f78b5b54f8ee5cbb4be3b09e82b9bf61d3/digest_supergroups.py#L284

**Comment by 91DarioDev** [comment]
https://github.com/91DarioDev/TopSupergroupsBot/commit/5105544cfa24837261d52167eaf7875c104540d9 fixed
