### ISSUE TITLE
TypeError: groupleaderboard() got an unexpected keyword argument 'args'

### ISSUE THREAD

**Issue by 91DarioDev** [91DarioDev/TopSupergroupsBot#68]
https://github.com/91DarioDev/topsupergroupsbot/blob/67dd3e881f6d4085f2b58937aaee62fa4628f581/topsupergroupsbot/leaderboards.py#L397

issuing /groupleaderboard command:

```Traceback (most recent call last):
  File "C:\Users\dario\AppData\Local\Programs\Python\Python36\lib\site-packages\telegram\ext\dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "C:\Users\dario\AppData\Local\Programs\Python\Python36\lib\site-packages\telegram\ext\commandhandler.py", line 171, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "d:\documents\bot telegram\topsupergroupsbot\topsupergroupsbot\utils.py", line 95, in wrapped
    return func(bot, update, *args, **kwargs)
TypeError: groupleaderboard() got an unexpected keyword argument 'args'```

**Comment by 91DarioDev** [comment]
#69
